[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "langchain-openai>=1.5.2",
    "mcp[cli]>=2.1.1",
    "langgraph>=1.2.11",
    "openai-whisper>=20250625",
    "python-multipart>=0.0.32",
    "uvicorn[standard]>=0.52.3",
]
